extractor:
  name: postgres
  params:
    conn_str: postgresql://postgres:!NTpatn2549@host.docker.internal:5433/postgres
    schema: bronze
    table: source_news_articles_newsapi
    fetch_size: 5000
    partition_column: sf_id
    lower_bound: 1
    upper_bound: 100000
    num_partitions: 4
